### ISSUE TITLE
Exclude "Version" global variable

### ISSUE THREAD

**Issue by Seirdy** [leighmcculloch/gochecknoglobals#26]
Many projects populate a "Version" variable at build-time using ldflags. For instance, a Makefile might set a Makefile variable to the latest Git tag and rev, and pass it to a "Version" variable through `-X`.

Doing so makes it easy for binaries to include version info (e.g. for a CLI program to print the version number when passed the `-v` flag). This is a good use-case for a global variable and shouldn't be considered an error, as long as there's only one per project.

**Comment by leighmcculloch** [comment]
That's a good point. I think you can get along this limitation by putting the declaration of the variable in a file that you exclude from linting.

We could make an exception for global variables with name `version`. There's always the chance that folks use a different name or need other variables too.

Another thought is whether this is necessary now that the modules version is extractable from Go binaries. For example you can get the version of a binary with `"runtime/debug".ReadBuildInfo()`.

**Comment by Seirdy** [comment]
On Thu, Sep 09, 2021 at 07:51:43PM -0700, Leigh McCulloch wrote:
>Another thought is whether this is necessary now that the modules 
>version is extractable from Go binaries. For example you can get the 
>version of a binary with `"runtime/debug".ReadBuildInfo()`.

My current understanding is that BuildInfo for Main modules always 
reports (devel), so it's not useful for binaries; a binary's version 
needs to be set during link-time or hard-coded.

-- 
/Seirdy

**Comment by leighmcculloch** [comment]
@Seirdy I forgot that this is already supported, you just need to use the variable name `version` instead of `Version`. 

https://github.com/leighmcculloch/gochecknoglobals/blob/fb0abda3d9aa53cbb3dc7f2df2f490f238d4ec10/checknoglobals/check_no_globals.go#L51-L54

Closing because I think this addresses your request, but please reopen if not.
