### ISSUE TITLE
checks _test.go

### ISSUE THREAD

**Issue by uselessdetails** [leighmcculloch/gochecknoglobals#34]
Default on...

```
pixley@M-C02DQ6AMML85> golangci-lint --version
golangci-lint has version 1.49.0 built from cc2d97f3 on 2022-08-24T10:24:37Z
pixley@M-C02DQ6AMML85> uname -a
Darwin M-C02DQ6AMML85 21.6.0 Darwin Kernel Version 21.6.0: Wed Aug 10 14:25:27 PDT 2022; root:xnu-8020.141.5~2/RELEASE_X86_64 x86_64
```

checks _test.go files.  I wish I could turn this off but I don't see any yaml config for this.

So... two errors, one may not be yours.  1) golangci-lint should not check _test.go files by default and 2) I wish there were a yaml option for me to explicitly turn it off.

**Comment by bombsimon** [comment]
The default value to check tests is `true` in `golangci-lint` and there is an option to switch it to false (which will apply for all linters). See https://golangci-lint.run/usage/configuration/#run-configuration

```yaml
run:
  # Include test files or not.
  # Default: true
  tests: false
```
