### ISSUE TITLE
Ignore struct acting as const?

### ISSUE THREAD

**Issue by tylerb** [leighmcculloch/gochecknoglobals#8]
Hey there!

First off, I just wanted to say thanks for writing this linter!

I was hoping to get your opinion on a possible change regarding a global variable that is acting as a constant. Let me explain:

It is common to see something like

```
const AuthenticationRoleAdmin = "admin"
const AuthenticationRoleGuest = "guest"
```

However, I prefer to organize those kinds of constants inside a struct so the API surface area is smaller. For example,

```
var AuthenticationRoles = struct {
	Admin string
	Guest string
}{
	Admin: "admin",
	Guest: "guest",
}
```

This allows me to have as many `AuthenticationRoles` as I want, without each one showing up, individually, at the top-level of the api. It's much nicer (IMO) to write `services.AuthenticationRoles.Admin`.

What would you think about having an option to ignore an anonymous global struct like this?

Thanks!

**Comment by leighmcculloch** [comment]
Hi @tylerb, thanks for opening the issue.

I think it'd be hard to identify a struct var intended for use as a const vs intended for use as a var. There was an issue golang/go#359 to make it possible to declare a const struct and that would more clearly offer us a solution to this but it's been closed on the basis that it's a rare use case. The fact that a global var uses an anonymous struct doesn't make it any less likely to cause side-effects which is primarily what the linter is attempting to prevent.

To move forward with this I think one of these would need to occur:

1. The language support const's with a struct. i.e. golang/go#359
2. The linter would need to know that the variable is to be treated like a const, and would then need to parse all uses of the struct to ensure it never changed.

Option 1 has been dismissed by the Go team and option 2 would be complex.

Did you have any other ideas?

**Comment by tylerb** [comment]
Thanks for the response!

That all makes sense. It's a shame the go team closed it. I think it could be useful. Then again, maybe I'm the one that needs to change. ;)

As it stands, I don't think it's worth the extra complexity in `gochecknoglobals` to implement option 2.
